// Autogenerated header *DO NOT* modify manually

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
    uint64_t _0;
} Matrix;

typedef struct {
    Matrix u;
    Matrix s;
    Matrix v;
} SVD;

void copy_matrix(Matrix matrix, double *to, uintptr_t size);

Matrix create_matrix(double *values, uint64_t cols, uint64_t rows);

Matrix fast_ica(Matrix whitened_matrix,
                uint64_t n_components,
                uint64_t max_iter,
                double conv_threshold,
                double alpha,
                uint32_t cfid);

void free_matrix(Matrix matrix);

void free_svd(SVD svd);

void matrix_dims(Matrix hmatrix, uint64_t *cols, uint64_t *rows);

void move_matrix(Matrix matrix, double *to, uintptr_t size);

SVD normalized_svd(Matrix matrix);

Matrix pca_whitening(Matrix matrix, SVD svd);

void print_matrix(Matrix matrix);

Matrix reduced_dimension_repr(Matrix matrix, Matrix svd_u, uint64_t ncols);

Matrix rotated_data_matrix(Matrix matrix, Matrix svd_u);

void set_backend(uintptr_t backend_id);

Matrix zca_whitening(Matrix matrix, SVD svd);
